@extends('layouts.app')
@section('content')
   <div class="container-fluid pt-4 pb-5">
    <ul class="nav nav-tabs nav-justified md-tabs bg-primary" id="myTabJust" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="home-tab-just" data-toggle="tab" href="#seafreight-just" role="tab" aria-controls="seafreight-just" aria-selected="true">Sea Freight</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" id="airfreight-tab-just" data-toggle="tab" href="#airfreight-just" role="tab" aria-controls="airfreight-just" aria-selected="false">Air Freight</a>
        </li>
    </ul>
    <div class="tab-content card pt-5" id="myTabContentJust">
        <div class="tab-pane fade show active" id="seafreight-just" role="tabpanel" aria-labelledby="seafreight-tab-just">
            <!-- Default form subscription -->
            <div class="text-center border border-light p-5">

                <p class="h3 mb-4">Sea Freight</p>

                <p> Rates are subject to change and the figures generated by the system are approximations and actual amount paid may vary slightly due to customs rates and the exchange rate.</p>



                <!-- Weight -->
                <input type="text" id="shippingweight" class="form-control mb-4" placeholder="Enter Shipping Weight (lbs)">
                <!-- Shipping Length -->
                <input type="text" id="shippinglength" class="form-control mb-4" placeholder="Enter Shipping Length">
                <!-- Width -->
                <input type="text" id="shippingwidth" class="form-control mb-4" placeholder="Enter Shipping Width">
                <!-- Weight -->
                <input type="text" id="shippingweight" class="form-control mb-4" placeholder="Enter Shipping Weight (lbs)">

                <!-- Price -->
                <input type="number" id="itemprice" class="form-control mb-4" placeholder="Enter Item Price (usd)">
                <!--Result --> 
               <input type="text" id="result" class="form-control mb-4" placeholder="">


                <!-- Calculate button -->
                <button class="btn btn-info btn-block" type="submit">Calculate</button>


            </div>
            <!-- Default form subscription -->
        </div>
        <div class="tab-pane fade" id="airfreight-just" role="tabpanel" aria-labelledby="airfreight-tab-just">
            <!-- Default form subscription -->
            <form class="text-center border border-light p-5">

                <p class="h3 pb-5 mb-4">Air Freight Calculator</p>

                <!-- Weight -->
                <input type="text" id="shippingweight" class="form-control mb-4" placeholder="Enter Shipping Weight (lbs)">
                <!-- Price -->
                <input type="text" id="itemprice" class="form-control mb-4" placeholder="Enter Item cost (usd)">
                <!--Result --> 
               <input type="text" id="result" class="form-control mb-4" placeholder="">

                <!-- Calculate button -->
                <button class="btn btn-info btn-block" type="submit">Calculate</button>


            </form>
            <!-- Default form subscription -->
        </div>

    </div>


    
@endsection